stages: 
  - test
  - build
#  - deploy


test project: 
  stage: test
  image: node:14
  script:
    - cd frontend
    - yarn install
    - yarn test --coverage --updateSnapshot

build project:
  stage: build
  image: node:14
  script:
    - cd frontend
    - yarn install
    - yarn build
